<?xml version="1.0" encoding="utf-8"?><Database Name="DataStore" Class="DataStoreDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=WINCB185249-A48;Initial Catalog=DataStore;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DataStoreConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Table]" Member="Tables">
    <Type Name="Table">
      <Column Name="Fid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FriendName" Type="System.String" DbType="NChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Place" Type="System.String" DbType="NChar(25) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>